[project]
name = "haxmas-flask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
    "flask-limiter>=4.1.1",
    "gunicorn>=23.0.0",
]
